### PR TITLE
add new kind of display data, 

### PR DESCRIPTION
**Pull request by ehsan69h**
display origin data and changes data and ... on DataVisualState property

### CODE REVIEW

**Comment by abbaye** [comment]
I will check this weekend 😁 thank for your contribution

**Comment by abbaye** [comment]
it's merged, and work fine

can explain the utility of this new functionality ?

Thank you

**Comment by ehsan69h** [comment]
The first functionality user can see the previous value of bytes when need that by using the origin mode.
when users need to know and compare byte value changes can using "Changes" and "ChangesPercent" mode.
in the future can add the ability to increase and decrease values cluster of bytes.

**Comment by abbaye** [comment]
:smile:

**Comment by abbaye** [comment]
Super ! 

Thank for your support in my project.

**Comment by abbaye** [comment]
I want to add the ability to insert everywhere but I have not the time right now 😔

**Pull request merged**
