### PR TITLE
Fixed deleted byte behavior

### PR DESCRIPTION
**Pull request by Dimitrisvech**

### CODE REVIEW

**Comment by abbaye** [comment]
Dima, can you push updated directly,.

git say that have a conflited file :(

**Comment by abbaye** [comment]
Sorry it's my first pullrequest and I have make a mistake when have made revers :(

**Comment by Dimitrisvech** [comment]
Fixed it directly in master branch, delete should work as well :)

**Comment by abbaye** [comment]
Thank you Dima
I will not made this error two time :)






Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
-------- Message d'origine --------De : Dima S <notifications@github.com> Date : 17-05-28  07:27  (GMT-05:00) À : abbaye/WPFHexEditorControl <WPFHexEditorControl@noreply.github.com> Cc : Derek Tremblay <derektremblay666@gmail.com>, Review requested <review_requested@noreply.github.com> Objet : Re: [abbaye/WPFHexEditorControl] Fixed deleted byte behavior (#9) 
Fixed it directly in master branch, delete should work as well :)

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/abbaye/WPFHexEditorControl","title":"abbaye/WPFHexEditorControl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/abbaye/WPFHexEditorControl"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Dimitrisvech in #9: Fixed it directly in master branch, delete should work as well :)"}],"action":{"name":"View Pull Request","url":"https://github.com/abbaye/WPFHexEditorControl/pull/9#issuecomment-304507996"}}}

**Pull request merged**
