### PR TITLE
add future show bar chart to display in data line

### PR DESCRIPTION
**Pull request by ehsan69h**
image

### CODE REVIEW

**Comment by abbaye** [comment]
Will this panel be added next to the Stringbyte panel?

Possibility to view both ?

**Comment by abbaye** [comment]
Do you will add selection in this panel ?

**Comment by ehsan69h** [comment]
now config to show one of them. but in the base can show both of them. just must be config window grid.
not, this hasn't any reaction to the user now.

**Comment by abbaye** [comment]
I will test today and If I have the time I will configure to show both

On future it will need tu be selectable like other byte panel before the next nuget release

**Comment by abbaye** [comment]
Why we don't use the stingbyte ans render the graph ?? It's require less code.

**Comment by abbaye** [comment]
After testing a really think that it will be easier to implement BarChart using the StringByte control.

We will juste need tu add a Value Property and adjust OnRender...

After that, all control will work fine without code change (zoom, selection, etc etc ...) 

Can you check this on this way ?? It's a good idea this chart :smile:

**Comment by abbaye** [comment]
I'm testing an implementation with stringByte to show the chart. I think it will work good

**Comment by abbaye** [comment]
I @ehsan69h. Please check lastest code and give me a feedback please 😄 

I think you ban base the next evolution of barchart on this build.

Thank for you support and contribution

**Pull request merged**
